import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case korean
    case english
    case japanese
    case simplifiedChinese
    case traditionalChinese
    case german
    case french
    case spanish
    case portugueseBrazil
    case italian
    case russian

    var id: String { rawValue }

    var titleKey: String {
        switch self {
        case .korean: return "menu.language.korean"
        case .english: return "menu.language.english"
        case .japanese: return "menu.language.japanese"
        case .simplifiedChinese: return "menu.language.simplifiedChinese"
        case .traditionalChinese: return "menu.language.traditionalChinese"
        case .german: return "menu.language.german"
        case .french: return "menu.language.french"
        case .spanish: return "menu.language.spanish"
        case .portugueseBrazil: return "menu.language.portugueseBrazil"
        case .italian: return "menu.language.italian"
        case .russian: return "menu.language.russian"
        }
    }
}

final class LocalizationController: ObservableObject {
    nonisolated(unsafe) static let shared = LocalizationController()

    @Published private(set) var selectedLanguage: AppLanguage?

    private let defaultsKey = "appLanguageOverride"

    private init() {
        let storedValue = UserDefaults.standard.string(forKey: defaultsKey)
        selectedLanguage = AppLanguage(rawValue: storedValue ?? "")
    }

    func setLanguage(_ language: AppLanguage) {
        guard selectedLanguage != language else { return }
        selectedLanguage = language
        UserDefaults.standard.set(language.rawValue, forKey: defaultsKey)
    }
}

enum Localized {
    static var currentLanguage: AppLanguage {
        LocalizationController.shared.selectedLanguage
            ?? inferredLanguage(from: Locale.preferredLanguages.first)
    }

    static func inferredLanguage(from preferredLanguage: String?) -> AppLanguage {
        let preferred = preferredLanguage?.lowercased() ?? "en"
        if preferred.hasPrefix("ko") {
            return .korean
        }
        if preferred.hasPrefix("ja") {
            return .japanese
        }
        if preferred.contains("hant") {
            return .traditionalChinese
        }
        if preferred.hasPrefix("zh") {
            return .simplifiedChinese
        }
        if preferred.hasPrefix("de") {
            return .german
        }
        if preferred.hasPrefix("fr") {
            return .french
        }
        if preferred.hasPrefix("es") {
            return .spanish
        }
        if preferred.hasPrefix("pt") {
            return .portugueseBrazil
        }
        if preferred.hasPrefix("it") {
            return .italian
        }
        if preferred.hasPrefix("ru") {
            return .russian
        }
        return .english
    }

    static func string(_ key: String) -> String {
        activeTable[key] ?? english[key] ?? key
    }

    static func string(_ key: String, _ arguments: CVarArg...) -> String {
        String(format: string(key), locale: Locale.current, arguments: arguments)
    }

    private static var activeTable: [String: String] {
        let language = currentLanguage

        switch language {
        case .korean: return korean
        case .english: return english
        case .japanese: return japanese
        case .simplifiedChinese: return simplifiedChinese
        case .traditionalChinese: return traditionalChinese
        case .german: return german
        case .french: return french
        case .spanish: return spanish
        case .portugueseBrazil: return portugueseBrazil
        case .italian: return italian
        case .russian: return russian
        }
    }

    private static let english: [String: String] = [
        "app.chooseCursorFolder": "Choose a cursor folder",
        "app.rolesReady": "%d roles ready",
        "app.folderRequired": "Folder required",
        "app.openSettings": "Open Settings",
        "app.quit": "Quit",
        "app.cursors": "Cursors",
        "app.additionalCursors": "Additional Cursors",
        "app.additionalCursorUses": "Uses %@",
        "app.additionalCursorHint": "Most people won't need to change these.\nThey cover macOS cursor states that aren't often used and are mapped to the most similar existing cursor by default.",
        "app.noCursorLoaded": "No cursor loaded",
        "app.loadCursorFolderHint": "Load a cursor folder, then choose a role from the list to preview it.",
        "app.exportToMousecape": "Export as .cape File…",
        "app.automaticMatchFailed": "Automatic matching failed",
        "app.automaticMatchFailedArrowFallback": "Automatic matching failed · using arrow fallback",
        "app.manualOverride": "Manual override",
        "app.automaticallyMatched": "Automatically matched",
        "app.automaticallyMatchedFromFolder": "Automatically matched from the folder",
        "app.changeCursorFile": "Change Cursor File…",
        "app.arrowFallbackDescription": "A dedicated cursor for this role was not found, so the theme's arrow cursor is being used instead.",
        "app.automaticMatchKeywords": "Automatic Match Keywords",
        "app.inheritedMatchKeywords": "Inherited Match Keywords",
        "app.mousecape": "Mousecape",
        "app.currentSource": "Current Source",
        "app.automaticallyMatchedInsideSelectedFolder": "Automatically matched inside the selected folder",
        "app.status": "Status",
        "app.automaticMatchFailedArrowFallbackShort": "Automatic matching failed (using arrow fallback)",
        "app.cursorFolder": "Cursor Folder",
        "app.noFolderSelected": "No folder selected",
        "app.chooseFolder": "Choose Folder…",
        "app.cursorWillAppearHere": "The cursor will appear here after you load one.",
        "preview.large": "Large Preview",
        "preview.actualSize": "Actual Size",
        "export.authorLabel": "Author",
        "export.authorPlaceholder": "Enter the author name for Mousecape",
        "export.sizeLabel": "Cursor Size",
        "export.emptyAuthorTitle": "Use your Mac account name?",
        "export.emptyAuthorMessage": "If you leave the author field empty, this cape will be exported with \"%@\" as the author.",
        "export.useMacUserName": "Use Mac Account Name",
        "export.cancel": "Cancel",
        "export.unknownAuthor": "Unknown Author",
        "role.arrow": "Arrow",
        "role.text": "Text Selection",
        "role.link": "Link Selection",
        "role.location": "Drag",
        "role.precision": "Precision Selection",
        "role.move": "Move",
        "role.unavailable": "Unavailable",
        "role.busy": "Busy",
        "role.working": "Wait",
        "role.help": "Help",
        "role.handwriting": "Handwriting",
        "role.person": "Cell Selection",
        "role.alternate": "Alias",
        "role.verticalResize": "Vertical Resize",
        "role.horizontalResize": "Horizontal Resize",
        "role.diagonalResizeNWSE": "Diagonal Resize 1",
        "role.diagonalResizeNESW": "Diagonal Resize 2",
        "role.contextualMenu": "Contextual Menu",
        "role.dragCopy": "Drag Copy",
        "role.dragLink": "Drag Link",
        "role.disappearingItem": "Disappearing Item",
        "role.resizeUp": "Resize Up",
        "role.resizeDown": "Resize Down",
        "role.resizeLeft": "Resize Left",
        "role.resizeRight": "Resize Right",
        "role.verticalIBeam": "Vertical Text Selection",
        "status.startingUp": "Starting up...",
        "status.chooseCursorFolder": "Choose a cursor folder.",
        "status.supportedFiles": "Supported files are .ani and .cur.",
        "status.exportSuccess": "Exported Mousecape cape: %@",
        "status.exportFailure": "Cape export failed: %@",
        "status.loaded": "Loaded %@ · %d/%d roles mapped",
        "status.loadFailure": "Load failed: %@",
        "panel.chooseFolder": "Choose Folder",
        "panel.chooseCursor": "Choose Cursor",
        "panel.export": "Export",
        "menu.language": "Language",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "No theme folder is selected.",
        "error.themeFileMissing": "Theme file is missing: %@",
        "error.aniParsingFailed": "ANI parsing failed: %@",
        "error.unsupportedCursorPayload": "The cursor frame could not be read as an image.",
        "error.invalidThemeSelection.noCursorFiles": "This folder does not contain cursor files that can be used directly.\nChoose a folder that contains .ani or .cur files at the top level.",
        "error.unsupportedExtension": "Unsupported file extension: %@",
        "error.invalidRiffAconHeader": "The file does not have a RIFF ACON header.",
        "error.invalidChunkLength": "The chunk length is invalid.",
        "error.noFrames": "The file does not contain any frames.",
        "error.invalidIconChunkLength": "The icon chunk length is invalid.",
        "error.curTooShort": "The CUR data is too short.",
        "error.invalidCurHeader": "The file does not contain a valid CUR header.",
        "error.invalidCurEmbeddedRange": "The embedded CUR image range is invalid.",
        "error.noCursorsToExport": "There are no cursors to export."
    ]

    private static let korean: [String: String] = [
        "app.chooseCursorFolder": "커서 폴더를 선택하세요",
        "app.rolesReady": "%d개 역할 준비됨",
        "app.folderRequired": "폴더 확인 필요",
        "app.openSettings": "설정 열기",
        "app.quit": "종료",
        "app.cursors": "커서",
        "app.additionalCursors": "추가 커서",
        "app.additionalCursorUses": "%@ 사용",
        "app.additionalCursorHint": "보통은 이 항목들을 따로 바꿀 필요가 없습니다.\n자주 쓰이지 않는 macOS 커서 상태를 위한 항목이며, 기본적으로 가장 비슷한 기존 커서에 연결됩니다.",
        "app.noCursorLoaded": "불러온 커서가 없습니다",
        "app.loadCursorFolderHint": "커서 폴더를 불러온 뒤 왼쪽 목록에서 역할을 고르면 해당 커서를 표시합니다.",
        "app.exportToMousecape": ".cape 파일로 내보내기…",
        "app.automaticMatchFailed": "자동 매핑 실패",
        "app.automaticMatchFailedArrowFallback": "자동 매핑 실패 · 일반 커서 대체",
        "app.manualOverride": "수동 지정",
        "app.automaticallyMatched": "자동 매핑",
        "app.automaticallyMatchedFromFolder": "폴더에서 자동 매핑된 파일",
        "app.changeCursorFile": "커서 파일 변경…",
        "app.arrowFallbackDescription": "자동 매칭되는 전용 커서를 찾지 못해 이 테마의 일반 커서로 대체했습니다.",
        "app.automaticMatchKeywords": "자동 매핑 키워드",
        "app.inheritedMatchKeywords": "상속된 매핑 키워드",
        "app.mousecape": "Mousecape",
        "app.currentSource": "현재 소스",
        "app.automaticallyMatchedInsideSelectedFolder": "선택한 폴더 안에서 자동 매핑",
        "app.status": "상태",
        "app.automaticMatchFailedArrowFallbackShort": "자동 매핑 실패 (일반 커서 대체)",
        "app.cursorFolder": "커서 폴더",
        "app.noFolderSelected": "선택된 폴더 없음",
        "app.chooseFolder": "폴더 선택…",
        "app.cursorWillAppearHere": "커서를 불러오면 여기에 표시됩니다.",
        "preview.large": "크게 보기",
        "preview.actualSize": "실제 크기",
        "export.authorLabel": "제작자명",
        "export.authorPlaceholder": "Mousecape에 표시할 제작자명을 입력하세요",
        "export.sizeLabel": "커서 크기",
        "export.emptyAuthorTitle": "맥 사용자 이름으로 내보낼까요?",
        "export.emptyAuthorMessage": "제작자명을 비워두면 이 cape는 \"%@\" 이름으로 내보내집니다.",
        "export.useMacUserName": "맥 사용자 이름 사용",
        "export.cancel": "취소",
        "export.unknownAuthor": "알 수 없음",
        "role.arrow": "일반 선택",
        "role.text": "텍스트 선택",
        "role.link": "링크 선택",
        "role.location": "드래그",
        "role.precision": "정밀도 선택",
        "role.move": "이동",
        "role.unavailable": "사용 불가",
        "role.busy": "사용 중",
        "role.working": "대기",
        "role.help": "도움말",
        "role.handwriting": "손글씨",
        "role.person": "셀 선택",
        "role.alternate": "바로가기",
        "role.verticalResize": "수직 크기 조절",
        "role.horizontalResize": "수평 크기 조절",
        "role.diagonalResizeNWSE": "대각선 크기 조절 1",
        "role.diagonalResizeNESW": "대각선 크기 조절 2",
        "role.contextualMenu": "컨텍스트 메뉴",
        "role.dragCopy": "드래그 복사",
        "role.dragLink": "드래그 링크",
        "role.disappearingItem": "사라지는 항목",
        "role.resizeUp": "위로 크기 조절",
        "role.resizeDown": "아래로 크기 조절",
        "role.resizeLeft": "왼쪽으로 크기 조절",
        "role.resizeRight": "오른쪽으로 크기 조절",
        "role.verticalIBeam": "세로 텍스트 선택",
        "status.startingUp": "초기화 중...",
        "status.chooseCursorFolder": "커서 폴더를 선택하세요.",
        "status.supportedFiles": "지원하는 파일은 .ani 또는 .cur 입니다.",
        "status.exportSuccess": "Mousecape용 cape 내보내기 완료: %@",
        "status.exportFailure": "cape 내보내기 실패: %@",
        "status.loaded": "로드 완료: %@ · %d/%d개 역할 연결됨",
        "status.loadFailure": "불러오기 실패: %@",
        "panel.chooseFolder": "폴더 선택",
        "panel.chooseCursor": "커서 선택",
        "panel.export": "내보내기",
        "menu.language": "언어",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "테마 폴더가 선택되지 않았습니다.",
        "error.themeFileMissing": "테마 파일이 없습니다: %@",
        "error.aniParsingFailed": "ANI 파싱 실패: %@",
        "error.unsupportedCursorPayload": "커서 프레임을 이미지로 읽지 못했습니다.",
        "error.invalidThemeSelection.noCursorFiles": "이 폴더에는 바로 적용할 커서 파일이 없습니다.\n.ani 또는 .cur 파일이 직접 들어 있는 폴더를 선택하세요.",
        "error.unsupportedExtension": "지원하지 않는 확장자입니다: %@",
        "error.invalidRiffAconHeader": "RIFF ACON 헤더가 아닙니다.",
        "error.invalidChunkLength": "청크 길이가 잘못되었습니다.",
        "error.noFrames": "프레임이 없습니다.",
        "error.invalidIconChunkLength": "icon 청크 길이가 잘못되었습니다.",
        "error.curTooShort": "CUR 데이터가 너무 짧습니다.",
        "error.invalidCurHeader": "CUR 헤더가 아닙니다.",
        "error.invalidCurEmbeddedRange": "CUR 내부 이미지 범위가 잘못되었습니다.",
        "error.noCursorsToExport": "내보낼 커서가 없습니다."
    ]

    private static let japanese: [String: String] = [
        "app.chooseCursorFolder": "カーソルフォルダを選択してください",
        "app.rolesReady": "%d 個の役割を読み込み済み",
        "app.folderRequired": "フォルダの確認が必要です",
        "app.openSettings": "設定を開く",
        "app.quit": "終了",
        "app.cursors": "カーソル",
        "app.additionalCursors": "追加カーソル",
        "app.additionalCursorUses": "%@ を使用",
        "app.additionalCursorHint": "通常、これらを個別に変更する必要はありません。\nあまり使われない macOS のカーソル状態向けで、既定では最も似ている既存カーソルに割り当てられます。",
        "app.noCursorLoaded": "読み込まれたカーソルがありません",
        "app.loadCursorFolderHint": "カーソルフォルダを読み込んだあと、左の一覧から役割を選ぶとプレビューできます。",
        "app.exportToMousecape": ".cape ファイルとして書き出す…",
        "app.automaticMatchFailed": "自動マッチングに失敗しました",
        "app.automaticMatchFailedArrowFallback": "自動マッチング失敗・通常カーソルで代用",
        "app.manualOverride": "手動指定",
        "app.automaticallyMatched": "自動マッチング",
        "app.automaticallyMatchedFromFolder": "フォルダから自動マッチングされたファイル",
        "app.changeCursorFile": "カーソルファイルを変更…",
        "app.arrowFallbackDescription": "この役割専用のカーソルが見つからなかったため、このテーマの通常カーソルで代用しています。",
        "app.automaticMatchKeywords": "自動一致キーワード",
        "app.inheritedMatchKeywords": "継承された一致キーワード",
        "app.mousecape": "Mousecape",
        "app.currentSource": "現在のソース",
        "app.automaticallyMatchedInsideSelectedFolder": "選択したフォルダ内で自動マッチング",
        "app.status": "状態",
        "app.automaticMatchFailedArrowFallbackShort": "自動マッチング失敗（通常カーソルで代用）",
        "app.cursorFolder": "カーソルフォルダ",
        "app.noFolderSelected": "フォルダが選択されていません",
        "app.chooseFolder": "フォルダを選択…",
        "app.cursorWillAppearHere": "カーソルを読み込むとここに表示されます。",
        "export.authorLabel": "作者名",
        "export.authorPlaceholder": "Mousecape に表示する作者名を入力してください",
        "export.sizeLabel": "カーソルサイズ",
        "export.emptyAuthorTitle": "Mac のユーザー名で書き出しますか？",
        "export.emptyAuthorMessage": "作者名を空欄のままにすると、この cape は \"%@\" を作者名として書き出されます。",
        "export.useMacUserName": "Mac のユーザー名を使う",
        "export.cancel": "キャンセル",
        "export.unknownAuthor": "不明",
        "role.arrow": "通常選択",
        "role.text": "テキスト選択",
        "role.link": "リンク選択",
        "role.location": "ドラッグ",
        "role.precision": "精密選択",
        "role.move": "移動",
        "role.unavailable": "使用不可",
        "role.busy": "使用中",
        "role.working": "待機",
        "role.help": "ヘルプ",
        "role.handwriting": "手書き",
        "role.person": "セル選択",
        "role.alternate": "エイリアス",
        "role.verticalResize": "垂直サイズ変更",
        "role.horizontalResize": "水平サイズ変更",
        "role.diagonalResizeNWSE": "斜めサイズ変更 1",
        "role.diagonalResizeNESW": "斜めサイズ変更 2",
        "role.contextualMenu": "コンテキストメニュー",
        "role.dragCopy": "ドラッグコピー",
        "role.dragLink": "ドラッグリンク",
        "role.disappearingItem": "消える項目",
        "role.resizeUp": "上方向にサイズ変更",
        "role.resizeDown": "下方向にサイズ変更",
        "role.resizeLeft": "左方向にサイズ変更",
        "role.resizeRight": "右方向にサイズ変更",
        "role.verticalIBeam": "縦書きテキスト選択",
        "status.startingUp": "初期化中...",
        "status.chooseCursorFolder": "カーソルフォルダを選択してください。",
        "status.supportedFiles": "対応ファイルは .ani と .cur です。",
        "status.exportSuccess": "Mousecape 用 cape の書き出し完了: %@",
        "status.exportFailure": "cape の書き出しに失敗しました: %@",
        "status.loaded": "読み込み完了: %@ · %d/%d 個の役割を接続済み",
        "status.loadFailure": "読み込み失敗: %@",
        "panel.chooseFolder": "フォルダを選択",
        "panel.chooseCursor": "カーソルを選択",
        "panel.export": "書き出す",
        "menu.language": "言語",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "テーマフォルダが選択されていません。",
        "error.themeFileMissing": "テーマファイルが見つかりません: %@",
        "error.aniParsingFailed": "ANI の解析に失敗しました: %@",
        "error.unsupportedCursorPayload": "カーソルフレームを画像として読み取れませんでした。",
        "error.invalidThemeSelection.noCursorFiles": "このフォルダには直接使えるカーソルファイルがありません。\n最上位に .ani または .cur ファイルがあるフォルダを選択してください。",
        "error.unsupportedExtension": "未対応の拡張子です: %@",
        "error.invalidRiffAconHeader": "RIFF ACON ヘッダーではありません。",
        "error.invalidChunkLength": "チャンク長が正しくありません。",
        "error.noFrames": "フレームがありません。",
        "error.invalidIconChunkLength": "icon チャンク長が正しくありません。",
        "error.curTooShort": "CUR データが短すぎます。",
        "error.invalidCurHeader": "有効な CUR ヘッダーではありません。",
        "error.invalidCurEmbeddedRange": "CUR 内部画像の範囲が正しくありません。",
        "error.noCursorsToExport": "書き出すカーソルがありません。"
    ]

    private static let simplifiedChinese: [String: String] = [
        "app.chooseCursorFolder": "请选择光标文件夹",
        "app.rolesReady": "已准备 %d 个角色",
        "app.folderRequired": "需要检查文件夹",
        "app.openSettings": "打开设置",
        "app.quit": "退出",
        "app.cursors": "光标",
        "app.additionalCursors": "附加光标",
        "app.additionalCursorUses": "使用 %@",
        "app.additionalCursorHint": "通常不需要单独修改这些项目。\n这些项目用于不常使用的 macOS 光标状态，默认会映射到最相似的现有光标。",
        "app.noCursorLoaded": "没有已加载的光标",
        "app.loadCursorFolderHint": "加载光标文件夹后，可在左侧列表中选择角色进行预览。",
        "app.exportToMousecape": "导出为 .cape 文件…",
        "app.automaticMatchFailed": "自动匹配失败",
        "app.automaticMatchFailedArrowFallback": "自动匹配失败 · 使用普通光标替代",
        "app.manualOverride": "手动指定",
        "app.automaticallyMatched": "自动匹配",
        "app.automaticallyMatchedFromFolder": "从文件夹自动匹配的文件",
        "app.changeCursorFile": "更改光标文件…",
        "app.arrowFallbackDescription": "未找到此角色专用的光标，因此改用该主题的普通光标。",
        "app.automaticMatchKeywords": "自动匹配关键词",
        "app.inheritedMatchKeywords": "继承的匹配关键词",
        "app.mousecape": "Mousecape",
        "app.currentSource": "当前来源",
        "app.automaticallyMatchedInsideSelectedFolder": "在所选文件夹内自动匹配",
        "app.status": "状态",
        "app.automaticMatchFailedArrowFallbackShort": "自动匹配失败（使用普通光标替代）",
        "app.cursorFolder": "光标文件夹",
        "app.noFolderSelected": "未选择文件夹",
        "app.chooseFolder": "选择文件夹…",
        "app.cursorWillAppearHere": "加载光标后会显示在这里。",
        "export.authorLabel": "作者名",
        "export.authorPlaceholder": "请输入要在 Mousecape 中显示的作者名",
        "export.sizeLabel": "光标大小",
        "export.emptyAuthorTitle": "要使用 Mac 用户名导出吗？",
        "export.emptyAuthorMessage": "如果作者名留空，此 cape 将以“%@”作为作者名导出。",
        "export.useMacUserName": "使用 Mac 用户名",
        "export.cancel": "取消",
        "export.unknownAuthor": "未知",
        "role.arrow": "普通选择",
        "role.text": "文本选择",
        "role.link": "链接选择",
        "role.location": "拖动",
        "role.precision": "精确选择",
        "role.move": "移动",
        "role.unavailable": "不可用",
        "role.busy": "忙碌",
        "role.working": "等待",
        "role.help": "帮助",
        "role.handwriting": "手写",
        "role.person": "单元格选择",
        "role.alternate": "别名",
        "role.verticalResize": "垂直调整大小",
        "role.horizontalResize": "水平调整大小",
        "role.diagonalResizeNWSE": "对角线调整大小 1",
        "role.diagonalResizeNESW": "对角线调整大小 2",
        "role.contextualMenu": "上下文菜单",
        "role.dragCopy": "拖拷贝",
        "role.dragLink": "拖拽链接",
        "role.disappearingItem": "消失项目",
        "role.resizeUp": "向上调整大小",
        "role.resizeDown": "向下调整大小",
        "role.resizeLeft": "向左调整大小",
        "role.resizeRight": "向右调整大小",
        "role.verticalIBeam": "纵向文本选择",
        "status.startingUp": "正在初始化...",
        "status.chooseCursorFolder": "请选择光标文件夹。",
        "status.supportedFiles": "支持的文件格式为 .ani 和 .cur。",
        "status.exportSuccess": "已导出 Mousecape cape：%@",
        "status.exportFailure": "cape 导出失败：%@",
        "status.loaded": "已加载 %@ · 已映射 %d/%d 个角色",
        "status.loadFailure": "加载失败：%@",
        "panel.chooseFolder": "选择文件夹",
        "panel.chooseCursor": "选择光标",
        "panel.export": "导出",
        "menu.language": "语言",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "未选择主题文件夹。",
        "error.themeFileMissing": "缺少主题文件：%@",
        "error.aniParsingFailed": "ANI 解析失败：%@",
        "error.unsupportedCursorPayload": "无法将光标帧读取为图像。",
        "error.invalidThemeSelection.noCursorFiles": "此文件夹中没有可直接使用的光标文件。\n请选择顶层包含 .ani 或 .cur 文件的文件夹。",
        "error.unsupportedExtension": "不支持的扩展名：%@",
        "error.invalidRiffAconHeader": "不是有效的 RIFF ACON 头。",
        "error.invalidChunkLength": "块长度无效。",
        "error.noFrames": "没有帧。",
        "error.invalidIconChunkLength": "icon 块长度无效。",
        "error.curTooShort": "CUR 数据过短。",
        "error.invalidCurHeader": "不是有效的 CUR 头。",
        "error.invalidCurEmbeddedRange": "CUR 内嵌图像范围无效。",
        "error.noCursorsToExport": "没有可导出的光标。"
    ]

    private static let traditionalChinese: [String: String] = [
        "app.chooseCursorFolder": "請選擇游標資料夾",
        "app.rolesReady": "已準備 %d 個角色",
        "app.folderRequired": "需要確認資料夾",
        "app.openSettings": "打開設定",
        "app.quit": "結束",
        "app.cursors": "游標",
        "app.additionalCursors": "附加游標",
        "app.additionalCursorUses": "使用 %@",
        "app.additionalCursorHint": "通常不需要另外修改這些項目。\n這些項目用於不常使用的 macOS 游標狀態，預設會對應到最相似的既有游標。",
        "app.noCursorLoaded": "沒有已載入的游標",
        "app.loadCursorFolderHint": "載入游標資料夾後，可在左側列表中選擇角色進行預覽。",
        "app.exportToMousecape": "匯出為 .cape 檔案…",
        "app.automaticMatchFailed": "自動配對失敗",
        "app.automaticMatchFailedArrowFallback": "自動配對失敗 · 使用一般游標替代",
        "app.manualOverride": "手動指定",
        "app.automaticallyMatched": "自動配對",
        "app.automaticallyMatchedFromFolder": "從資料夾自動配對的檔案",
        "app.changeCursorFile": "變更游標檔案…",
        "app.arrowFallbackDescription": "找不到此角色專用的游標，因此改用此主題的一般游標。",
        "app.automaticMatchKeywords": "自動匹配關鍵字",
        "app.inheritedMatchKeywords": "繼承的匹配關鍵字",
        "app.mousecape": "Mousecape",
        "app.currentSource": "目前來源",
        "app.automaticallyMatchedInsideSelectedFolder": "在所選資料夾中自動配對",
        "app.status": "狀態",
        "app.automaticMatchFailedArrowFallbackShort": "自動配對失敗（使用一般游標替代）",
        "app.cursorFolder": "游標資料夾",
        "app.noFolderSelected": "未選擇資料夾",
        "app.chooseFolder": "選擇資料夾…",
        "app.cursorWillAppearHere": "載入游標後會顯示在這裡。",
        "export.authorLabel": "作者名",
        "export.authorPlaceholder": "請輸入要在 Mousecape 中顯示的作者名",
        "export.sizeLabel": "游標大小",
        "export.emptyAuthorTitle": "要使用 Mac 使用者名稱匯出嗎？",
        "export.emptyAuthorMessage": "若作者名留空，此 cape 將以「%@」作為作者名匯出。",
        "export.useMacUserName": "使用 Mac 使用者名稱",
        "export.cancel": "取消",
        "export.unknownAuthor": "未知",
        "role.arrow": "一般選擇",
        "role.text": "文字選擇",
        "role.link": "連結選擇",
        "role.location": "拖曳",
        "role.precision": "精確選擇",
        "role.move": "移動",
        "role.unavailable": "不可用",
        "role.busy": "忙碌",
        "role.working": "等待",
        "role.help": "說明",
        "role.handwriting": "手寫",
        "role.person": "儲存格選擇",
        "role.alternate": "別名",
        "role.verticalResize": "垂直調整大小",
        "role.horizontalResize": "水平調整大小",
        "role.diagonalResizeNWSE": "對角線調整大小 1",
        "role.diagonalResizeNESW": "對角線調整大小 2",
        "role.contextualMenu": "情境選單",
        "role.dragCopy": "拖曳複製",
        "role.dragLink": "拖曳連結",
        "role.disappearingItem": "消失項目",
        "role.resizeUp": "向上調整大小",
        "role.resizeDown": "向下調整大小",
        "role.resizeLeft": "向左調整大小",
        "role.resizeRight": "向右調整大小",
        "role.verticalIBeam": "垂直文字選取",
        "status.startingUp": "初始化中...",
        "status.chooseCursorFolder": "請選擇游標資料夾。",
        "status.supportedFiles": "支援的檔案格式為 .ani 與 .cur。",
        "status.exportSuccess": "已匯出 Mousecape cape：%@",
        "status.exportFailure": "cape 匯出失敗：%@",
        "status.loaded": "已載入 %@ · 已對應 %d/%d 個角色",
        "status.loadFailure": "載入失敗：%@",
        "panel.chooseFolder": "選擇資料夾",
        "panel.chooseCursor": "選擇游標",
        "panel.export": "匯出",
        "menu.language": "語言",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "未選擇主題資料夾。",
        "error.themeFileMissing": "缺少主題檔案：%@",
        "error.aniParsingFailed": "ANI 解析失敗：%@",
        "error.unsupportedCursorPayload": "無法將游標影格讀取為影像。",
        "error.invalidThemeSelection.noCursorFiles": "此資料夾中沒有可直接使用的游標檔案。\n請選擇頂層包含 .ani 或 .cur 檔案的資料夾。",
        "error.unsupportedExtension": "不支援的副檔名：%@",
        "error.invalidRiffAconHeader": "不是有效的 RIFF ACON 標頭。",
        "error.invalidChunkLength": "區塊長度無效。",
        "error.noFrames": "沒有影格。",
        "error.invalidIconChunkLength": "icon 區塊長度無效。",
        "error.curTooShort": "CUR 資料過短。",
        "error.invalidCurHeader": "不是有效的 CUR 標頭。",
        "error.invalidCurEmbeddedRange": "CUR 內嵌影像範圍無效。",
        "error.noCursorsToExport": "沒有可匯出的游標。"
    ]

    private static let german: [String: String] = [
        "app.chooseCursorFolder": "Wählen Sie einen Cursor-Ordner",
        "app.rolesReady": "%d Rollen bereit",
        "app.folderRequired": "Ordner erforderlich",
        "app.openSettings": "Einstellungen öffnen",
        "app.quit": "Beenden",
        "app.cursors": "Cursor",
        "app.additionalCursors": "Zusätzliche Cursor",
        "app.additionalCursorUses": "Verwendet %@",
        "app.additionalCursorHint": "Normalerweise müssen Sie diese nicht ändern.\nSie decken macOS-Cursorzustände ab, die nicht oft verwendet werden, und werden standardmäßig dem ähnlichsten vorhandenen Cursor zugeordnet.",
        "app.noCursorLoaded": "Kein Cursor geladen",
        "app.loadCursorFolderHint": "Laden Sie einen Cursor-Ordner und wählen Sie dann links eine Rolle zur Vorschau aus.",
        "app.exportToMousecape": "Als .cape-Datei exportieren…",
        "app.automaticMatchFailed": "Automatische Zuordnung fehlgeschlagen",
        "app.automaticMatchFailedArrowFallback": "Automatische Zuordnung fehlgeschlagen · Standardcursor als Ersatz",
        "app.manualOverride": "Manuelle Zuweisung",
        "app.automaticallyMatched": "Automatisch zugeordnet",
        "app.automaticallyMatchedFromFolder": "Automatisch aus dem Ordner zugeordnet",
        "app.changeCursorFile": "Cursor-Datei ändern…",
        "app.arrowFallbackDescription": "Für diese Rolle wurde kein eigener Cursor gefunden, daher wird stattdessen der Standardcursor des Themes verwendet.",
        "app.automaticMatchKeywords": "Schlüsselwörter für automatische Zuordnung",
        "app.inheritedMatchKeywords": "Übernommene Zuordnungsschlüsselwörter",
        "app.mousecape": "Mousecape",
        "app.currentSource": "Aktuelle Quelle",
        "app.automaticallyMatchedInsideSelectedFolder": "Im ausgewählten Ordner automatisch zugeordnet",
        "app.status": "Status",
        "app.automaticMatchFailedArrowFallbackShort": "Automatische Zuordnung fehlgeschlagen (Standardcursor als Ersatz)",
        "app.cursorFolder": "Cursor-Ordner",
        "app.noFolderSelected": "Kein Ordner ausgewählt",
        "app.chooseFolder": "Ordner wählen…",
        "app.cursorWillAppearHere": "Der Cursor wird hier angezeigt, sobald Sie einen laden.",
        "export.authorLabel": "Autor",
        "export.authorPlaceholder": "Autorname für Mousecape eingeben",
        "export.sizeLabel": "Cursorgröße",
        "export.emptyAuthorTitle": "Mac-Benutzernamen verwenden?",
        "export.emptyAuthorMessage": "Wenn Sie das Autorenfeld leer lassen, wird dieses Cape mit \"%@\" als Autor exportiert.",
        "export.useMacUserName": "Mac-Benutzernamen verwenden",
        "export.cancel": "Abbrechen",
        "export.unknownAuthor": "Unbekannt",
        "role.arrow": "Standardauswahl",
        "role.text": "Textauswahl",
        "role.link": "Linkauswahl",
        "role.location": "Ziehen",
        "role.precision": "Präzisionsauswahl",
        "role.move": "Bewegen",
        "role.unavailable": "Nicht verfügbar",
        "role.busy": "Beschäftigt",
        "role.working": "Warten",
        "role.help": "Hilfe",
        "role.handwriting": "Handschrift",
        "role.person": "Zellenauswahl",
        "role.alternate": "Alias",
        "role.verticalResize": "Vertikal skalieren",
        "role.horizontalResize": "Horizontal skalieren",
        "role.diagonalResizeNWSE": "Diagonale Größenänderung 1",
        "role.diagonalResizeNESW": "Diagonale Größenänderung 2",
        "role.contextualMenu": "Kontextmenü",
        "role.dragCopy": "Ziehen zum Kopieren",
        "role.dragLink": "Ziehen zum Verknüpfen",
        "role.disappearingItem": "Verschwindendes Element",
        "role.resizeUp": "Nach oben vergrößern",
        "role.resizeDown": "Nach unten vergrößern",
        "role.resizeLeft": "Nach links vergrößern",
        "role.resizeRight": "Nach rechts vergrößern",
        "role.verticalIBeam": "Vertikale Textauswahl",
        "status.startingUp": "Initialisierung...",
        "status.chooseCursorFolder": "Wählen Sie einen Cursor-Ordner.",
        "status.supportedFiles": "Unterstützte Dateien sind .ani und .cur.",
        "status.exportSuccess": "Mousecape-Cape exportiert: %@",
        "status.exportFailure": "Cape-Export fehlgeschlagen: %@",
        "status.loaded": "%@ geladen · %d/%d Rollen zugeordnet",
        "status.loadFailure": "Laden fehlgeschlagen: %@",
        "panel.chooseFolder": "Ordner wählen",
        "panel.chooseCursor": "Cursor wählen",
        "panel.export": "Exportieren",
        "menu.language": "Sprache",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "Kein Theme-Ordner ausgewählt.",
        "error.themeFileMissing": "Theme-Datei fehlt: %@",
        "error.aniParsingFailed": "ANI-Analyse fehlgeschlagen: %@",
        "error.unsupportedCursorPayload": "Der Cursor-Frame konnte nicht als Bild gelesen werden.",
        "error.invalidThemeSelection.noCursorFiles": "Dieser Ordner enthält keine direkt nutzbaren Cursor-Dateien.\nWählen Sie einen Ordner, der .ani- oder .cur-Dateien auf oberster Ebene enthält.",
        "error.unsupportedExtension": "Nicht unterstützte Dateiendung: %@",
        "error.invalidRiffAconHeader": "Die Datei hat keinen gültigen RIFF-ACON-Header.",
        "error.invalidChunkLength": "Die Chunk-Länge ist ungültig.",
        "error.noFrames": "Die Datei enthält keine Frames.",
        "error.invalidIconChunkLength": "Die Länge des icon-Chunks ist ungültig.",
        "error.curTooShort": "Die CUR-Daten sind zu kurz.",
        "error.invalidCurHeader": "Die Datei enthält keinen gültigen CUR-Header.",
        "error.invalidCurEmbeddedRange": "Der eingebettete CUR-Bereich ist ungültig.",
        "error.noCursorsToExport": "Es gibt keine Cursor zum Exportieren."
    ]

    private static let french: [String: String] = [
        "app.chooseCursorFolder": "Choisissez un dossier de curseurs",
        "app.rolesReady": "%d rôles prêts",
        "app.folderRequired": "Dossier requis",
        "app.openSettings": "Ouvrir les réglages",
        "app.quit": "Quitter",
        "app.cursors": "Curseurs",
        "app.additionalCursors": "Curseurs supplémentaires",
        "app.additionalCursorUses": "Utilise %@",
        "app.additionalCursorHint": "Vous n'aurez généralement pas besoin de modifier ces éléments.\nIls couvrent des états de curseur macOS peu utilisés et sont associés par défaut au curseur existant le plus similaire.",
        "app.noCursorLoaded": "Aucun curseur chargé",
        "app.loadCursorFolderHint": "Chargez un dossier de curseurs, puis choisissez un role dans la liste à gauche pour l’aperçu.",
        "app.exportToMousecape": "Exporter en fichier .cape…",
        "app.automaticMatchFailed": "Échec de la correspondance automatique",
        "app.automaticMatchFailedArrowFallback": "Échec de la correspondance automatique · curseur normal utilisé",
        "app.manualOverride": "Remplacement manuel",
        "app.automaticallyMatched": "Correspondance automatique",
        "app.automaticallyMatchedFromFolder": "Fichier associé automatiquement depuis le dossier",
        "app.changeCursorFile": "Changer le fichier du curseur…",
        "app.arrowFallbackDescription": "Aucun curseur dédié n’a été trouvé pour ce role. Le curseur normal du thème est utilisé à la place.",
        "app.automaticMatchKeywords": "Mots-clés de correspondance automatique",
        "app.inheritedMatchKeywords": "Mots-clés de correspondance hérités",
        "app.mousecape": "Mousecape",
        "app.currentSource": "Source actuelle",
        "app.automaticallyMatchedInsideSelectedFolder": "Correspondance automatique dans le dossier sélectionné",
        "app.status": "État",
        "app.automaticMatchFailedArrowFallbackShort": "Correspondance automatique échouée (curseur normal utilisé)",
        "app.cursorFolder": "Dossier de curseurs",
        "app.noFolderSelected": "Aucun dossier sélectionné",
        "app.chooseFolder": "Choisir un dossier…",
        "app.cursorWillAppearHere": "Le curseur apparaîtra ici après chargement.",
        "export.authorLabel": "Auteur",
        "export.authorPlaceholder": "Saisissez le nom d’auteur pour Mousecape",
        "export.sizeLabel": "Taille du curseur",
        "export.emptyAuthorTitle": "Utiliser le nom d’utilisateur du Mac ?",
        "export.emptyAuthorMessage": "Si vous laissez le champ auteur vide, ce cape sera exporté avec \"%@\" comme auteur.",
        "export.useMacUserName": "Utiliser le nom d’utilisateur du Mac",
        "export.cancel": "Annuler",
        "export.unknownAuthor": "Inconnu",
        "role.arrow": "Sélection normale",
        "role.text": "Sélection de texte",
        "role.link": "Sélection de lien",
        "role.location": "Glisser",
        "role.precision": "Sélection précise",
        "role.move": "Déplacer",
        "role.unavailable": "Indisponible",
        "role.busy": "Occupé",
        "role.working": "Attente",
        "role.help": "Aide",
        "role.handwriting": "Écriture manuscrite",
        "role.person": "Sélection de cellule",
        "role.alternate": "Alias",
        "role.verticalResize": "Redimensionnement vertical",
        "role.horizontalResize": "Redimensionnement horizontal",
        "role.diagonalResizeNWSE": "Redimensionnement diagonal 1",
        "role.diagonalResizeNESW": "Redimensionnement diagonal 2",
        "role.contextualMenu": "Menu contextuel",
        "role.dragCopy": "Glisser pour copier",
        "role.dragLink": "Glisser pour lier",
        "role.disappearingItem": "Élément disparaissant",
        "role.resizeUp": "Redimensionner vers le haut",
        "role.resizeDown": "Redimensionner vers le bas",
        "role.resizeLeft": "Redimensionner vers la gauche",
        "role.resizeRight": "Redimensionner vers la droite",
        "role.verticalIBeam": "Sélection de texte verticale",
        "status.startingUp": "Initialisation...",
        "status.chooseCursorFolder": "Choisissez un dossier de curseurs.",
        "status.supportedFiles": "Les fichiers pris en charge sont .ani et .cur.",
        "status.exportSuccess": "Cape Mousecape exporté : %@",
        "status.exportFailure": "Échec de l’export du cape : %@",
        "status.loaded": "%@ chargé · %d/%d rôles associés",
        "status.loadFailure": "Échec du chargement : %@",
        "panel.chooseFolder": "Choisir un dossier",
        "panel.chooseCursor": "Choisir un curseur",
        "panel.export": "Exporter",
        "menu.language": "Langue",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "Aucun dossier de thème sélectionné.",
        "error.themeFileMissing": "Fichier de thème introuvable : %@",
        "error.aniParsingFailed": "Échec de l’analyse ANI : %@",
        "error.unsupportedCursorPayload": "Impossible de lire l’image du frame du curseur.",
        "error.invalidThemeSelection.noCursorFiles": "Ce dossier ne contient pas de fichiers de curseur directement utilisables.\nChoisissez un dossier contenant des fichiers .ani ou .cur à la racine.",
        "error.unsupportedExtension": "Extension non prise en charge : %@",
        "error.invalidRiffAconHeader": "Le fichier ne possède pas d’en-tête RIFF ACON valide.",
        "error.invalidChunkLength": "La longueur du bloc est invalide.",
        "error.noFrames": "Le fichier ne contient aucune frame.",
        "error.invalidIconChunkLength": "La longueur du bloc icon est invalide.",
        "error.curTooShort": "Les données CUR sont trop courtes.",
        "error.invalidCurHeader": "Le fichier ne contient pas d’en-tête CUR valide.",
        "error.invalidCurEmbeddedRange": "La plage de l’image CUR intégrée est invalide.",
        "error.noCursorsToExport": "Aucun curseur à exporter."
    ]

    private static let spanish: [String: String] = [
        "app.chooseCursorFolder": "Elige una carpeta de cursores",
        "app.rolesReady": "%d roles listos",
        "app.folderRequired": "Se requiere una carpeta",
        "app.openSettings": "Abrir ajustes",
        "app.quit": "Salir",
        "app.cursors": "Cursores",
        "app.additionalCursors": "Cursores adicionales",
        "app.additionalCursorUses": "Usa %@",
        "app.additionalCursorHint": "Normalmente no necesitarás cambiar estos elementos.\nCubren estados de cursor de macOS que no se usan con frecuencia y, por defecto, se asignan al cursor existente más similar.",
        "app.noCursorLoaded": "No hay cursores cargados",
        "app.loadCursorFolderHint": "Carga una carpeta de cursores y luego elige un rol en la lista de la izquierda para ver la vista previa.",
        "app.exportToMousecape": "Exportar como archivo .cape…",
        "app.automaticMatchFailed": "Falló la coincidencia automática",
        "app.automaticMatchFailedArrowFallback": "Falló la coincidencia automática · usando cursor normal",
        "app.manualOverride": "Asignación manual",
        "app.automaticallyMatched": "Coincidencia automática",
        "app.automaticallyMatchedFromFolder": "Archivo asignado automáticamente desde la carpeta",
        "app.changeCursorFile": "Cambiar archivo de cursor…",
        "app.arrowFallbackDescription": "No se encontró un cursor dedicado para este rol, así que se usa el cursor normal del tema.",
        "app.automaticMatchKeywords": "Palabras clave de coincidencia automática",
        "app.inheritedMatchKeywords": "Palabras clave de coincidencia heredadas",
        "app.mousecape": "Mousecape",
        "app.currentSource": "Origen actual",
        "app.automaticallyMatchedInsideSelectedFolder": "Coincidencia automática dentro de la carpeta seleccionada",
        "app.status": "Estado",
        "app.automaticMatchFailedArrowFallbackShort": "Falló la coincidencia automática (usando cursor normal)",
        "app.cursorFolder": "Carpeta de cursores",
        "app.noFolderSelected": "No se ha seleccionado ninguna carpeta",
        "app.chooseFolder": "Elegir carpeta…",
        "app.cursorWillAppearHere": "El cursor aparecerá aquí después de cargarlo.",
        "export.authorLabel": "Autor",
        "export.authorPlaceholder": "Introduce el nombre del autor para Mousecape",
        "export.sizeLabel": "Tamaño del cursor",
        "export.emptyAuthorTitle": "¿Usar el nombre de usuario de tu Mac?",
        "export.emptyAuthorMessage": "Si dejas vacío el campo del autor, este cape se exportará con \"%@\" como autor.",
        "export.useMacUserName": "Usar nombre de usuario del Mac",
        "export.cancel": "Cancelar",
        "export.unknownAuthor": "Desconocido",
        "role.arrow": "Selección normal",
        "role.text": "Selección de texto",
        "role.link": "Selección de enlace",
        "role.location": "Arrastrar",
        "role.precision": "Selección precisa",
        "role.move": "Mover",
        "role.unavailable": "No disponible",
        "role.busy": "Ocupado",
        "role.working": "Esperando",
        "role.help": "Ayuda",
        "role.handwriting": "Escritura a mano",
        "role.person": "Selección de celda",
        "role.alternate": "Alias",
        "role.verticalResize": "Redimensionado vertical",
        "role.horizontalResize": "Redimensionado horizontal",
        "role.diagonalResizeNWSE": "Redimensionado diagonal 1",
        "role.diagonalResizeNESW": "Redimensionado diagonal 2",
        "role.contextualMenu": "Menú contextual",
        "role.dragCopy": "Arrastrar para copiar",
        "role.dragLink": "Arrastrar para enlazar",
        "role.disappearingItem": "Elemento que desaparece",
        "role.resizeUp": "Redimensionar hacia arriba",
        "role.resizeDown": "Redimensionar hacia abajo",
        "role.resizeLeft": "Redimensionar hacia la izquierda",
        "role.resizeRight": "Redimensionar hacia la derecha",
        "role.verticalIBeam": "Selección de texto vertical",
        "status.startingUp": "Iniciando...",
        "status.chooseCursorFolder": "Elige una carpeta de cursores.",
        "status.supportedFiles": "Los archivos compatibles son .ani y .cur.",
        "status.exportSuccess": "Cape de Mousecape exportado: %@",
        "status.exportFailure": "Error al exportar el cape: %@",
        "status.loaded": "%@ cargado · %d/%d roles asignados",
        "status.loadFailure": "Error al cargar: %@",
        "panel.chooseFolder": "Elegir carpeta",
        "panel.chooseCursor": "Elegir cursor",
        "panel.export": "Exportar",
        "menu.language": "Idioma",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "No se ha seleccionado ninguna carpeta de tema.",
        "error.themeFileMissing": "Falta el archivo del tema: %@",
        "error.aniParsingFailed": "Error al analizar ANI: %@",
        "error.unsupportedCursorPayload": "No se pudo leer el fotograma del cursor como imagen.",
        "error.invalidThemeSelection.noCursorFiles": "Esta carpeta no contiene archivos de cursor que puedan usarse directamente.\nElige una carpeta que contenga archivos .ani o .cur en el nivel superior.",
        "error.unsupportedExtension": "Extensión no compatible: %@",
        "error.invalidRiffAconHeader": "El archivo no tiene un encabezado RIFF ACON válido.",
        "error.invalidChunkLength": "La longitud del bloque es inválida.",
        "error.noFrames": "El archivo no contiene fotogramas.",
        "error.invalidIconChunkLength": "La longitud del bloque icon es inválida.",
        "error.curTooShort": "Los datos CUR son demasiado cortos.",
        "error.invalidCurHeader": "El archivo no contiene un encabezado CUR válido.",
        "error.invalidCurEmbeddedRange": "El rango de la imagen CUR incrustada es inválido.",
        "error.noCursorsToExport": "No hay cursores para exportar."
    ]

    private static let portugueseBrazil: [String: String] = [
        "app.chooseCursorFolder": "Escolha uma pasta de cursores",
        "app.rolesReady": "%d funções prontas",
        "app.folderRequired": "Pasta necessária",
        "app.openSettings": "Abrir Ajustes",
        "app.quit": "Sair",
        "app.cursors": "Cursores",
        "app.additionalCursors": "Cursores adicionais",
        "app.additionalCursorUses": "Usa %@",
        "app.additionalCursorHint": "Normalmente você não precisará alterar estes itens.\nEles cobrem estados de cursor do macOS que não são usados com frequência e, por padrão, são mapeados para o cursor existente mais semelhante.",
        "app.noCursorLoaded": "Nenhum cursor carregado",
        "app.loadCursorFolderHint": "Carregue uma pasta de cursores e depois escolha uma função na lista à esquerda para visualizar.",
        "app.exportToMousecape": "Exportar como arquivo .cape…",
        "app.automaticMatchFailed": "Falha na correspondência automática",
        "app.automaticMatchFailedArrowFallback": "Falha na correspondência automática · usando o cursor padrão",
        "app.manualOverride": "Substituição manual",
        "app.automaticallyMatched": "Correspondência automática",
        "app.automaticallyMatchedFromFolder": "Arquivo associado automaticamente da pasta",
        "app.changeCursorFile": "Alterar arquivo do cursor…",
        "app.arrowFallbackDescription": "Não foi encontrado um cursor dedicado para esta função, então o cursor padrão do tema está sendo usado no lugar.",
        "app.automaticMatchKeywords": "Palavras-chave de correspondência automática",
        "app.inheritedMatchKeywords": "Palavras-chave de correspondência herdadas",
        "app.mousecape": "Mousecape",
        "app.currentSource": "Fonte atual",
        "app.automaticallyMatchedInsideSelectedFolder": "Correspondência automática dentro da pasta selecionada",
        "app.status": "Status",
        "app.automaticMatchFailedArrowFallbackShort": "Falha na correspondência automática (usando cursor padrão)",
        "app.cursorFolder": "Pasta de cursores",
        "app.noFolderSelected": "Nenhuma pasta selecionada",
        "app.chooseFolder": "Escolher pasta…",
        "app.cursorWillAppearHere": "O cursor aparecerá aqui depois que você carregar um.",
        "export.authorLabel": "Autor",
        "export.authorPlaceholder": "Digite o nome do autor para o Mousecape",
        "export.sizeLabel": "Tamanho do cursor",
        "export.emptyAuthorTitle": "Usar o nome de usuário do Mac?",
        "export.emptyAuthorMessage": "Se você deixar o campo de autor vazio, este cape será exportado com \"%@\" como autor.",
        "export.useMacUserName": "Usar nome de usuário do Mac",
        "export.cancel": "Cancelar",
        "export.unknownAuthor": "Desconhecido",
        "role.arrow": "Seleção padrão",
        "role.text": "Seleção de texto",
        "role.link": "Seleção de link",
        "role.location": "Arrastar",
        "role.precision": "Seleção precisa",
        "role.move": "Mover",
        "role.unavailable": "Indisponível",
        "role.busy": "Ocupado",
        "role.working": "Aguardando",
        "role.help": "Ajuda",
        "role.handwriting": "Escrita à mão",
        "role.person": "Seleção de célula",
        "role.alternate": "Alias",
        "role.verticalResize": "Redimensionamento vertical",
        "role.horizontalResize": "Redimensionamento horizontal",
        "role.diagonalResizeNWSE": "Redimensionamento diagonal 1",
        "role.diagonalResizeNESW": "Redimensionamento diagonal 2",
        "role.contextualMenu": "Menu contextual",
        "role.dragCopy": "Arrastar para copiar",
        "role.dragLink": "Arrastar para link",
        "role.disappearingItem": "Item desaparecendo",
        "role.resizeUp": "Redimensionar para cima",
        "role.resizeDown": "Redimensionar para baixo",
        "role.resizeLeft": "Redimensionar para a esquerda",
        "role.resizeRight": "Redimensionar para a direita",
        "role.verticalIBeam": "Seleção vertical de texto",
        "status.startingUp": "Iniciando...",
        "status.chooseCursorFolder": "Escolha uma pasta de cursores.",
        "status.supportedFiles": "Os arquivos compatíveis são .ani e .cur.",
        "status.exportSuccess": "Cape do Mousecape exportado: %@",
        "status.exportFailure": "Falha ao exportar o cape: %@",
        "status.loaded": "%@ carregado · %d/%d funções mapeadas",
        "status.loadFailure": "Falha ao carregar: %@",
        "panel.chooseFolder": "Escolher pasta",
        "panel.chooseCursor": "Escolher cursor",
        "panel.export": "Exportar",
        "menu.language": "Idioma",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "Nenhuma pasta de tema foi selecionada.",
        "error.themeFileMissing": "Arquivo de tema ausente: %@",
        "error.aniParsingFailed": "Falha ao analisar ANI: %@",
        "error.unsupportedCursorPayload": "Não foi possível ler o quadro do cursor como imagem.",
        "error.invalidThemeSelection.noCursorFiles": "Esta pasta não contém arquivos de cursor que possam ser usados diretamente.\nEscolha uma pasta que contenha arquivos .ani ou .cur no nível superior.",
        "error.unsupportedExtension": "Extensão não compatível: %@",
        "error.invalidRiffAconHeader": "O arquivo não possui um cabeçalho RIFF ACON válido.",
        "error.invalidChunkLength": "O comprimento do bloco é inválido.",
        "error.noFrames": "O arquivo não contém quadros.",
        "error.invalidIconChunkLength": "O comprimento do bloco icon é inválido.",
        "error.curTooShort": "Os dados CUR são curtos demais.",
        "error.invalidCurHeader": "O arquivo não contém um cabeçalho CUR válido.",
        "error.invalidCurEmbeddedRange": "O intervalo da imagem CUR incorporada é inválido.",
        "error.noCursorsToExport": "Não há cursores para exportar."
    ]

    private static let italian: [String: String] = [
        "app.chooseCursorFolder": "Scegli una cartella di cursori",
        "app.rolesReady": "%d ruoli pronti",
        "app.folderRequired": "Cartella richiesta",
        "app.openSettings": "Apri Impostazioni",
        "app.quit": "Esci",
        "app.cursors": "Cursori",
        "app.additionalCursors": "Cursori aggiuntivi",
        "app.additionalCursorUses": "Usa %@",
        "app.additionalCursorHint": "Di solito non è necessario modificare questi elementi.\nCoprono stati del cursore macOS che non vengono usati spesso e, per impostazione predefinita, vengono associati al cursore esistente più simile.",
        "app.noCursorLoaded": "Nessun cursore caricato",
        "app.loadCursorFolderHint": "Carica una cartella di cursori, poi scegli un ruolo nell’elenco a sinistra per l’anteprima.",
        "app.exportToMousecape": "Esporta come file .cape…",
        "app.automaticMatchFailed": "Associazione automatica non riuscita",
        "app.automaticMatchFailedArrowFallback": "Associazione automatica non riuscita · uso del cursore standard",
        "app.manualOverride": "Sostituzione manuale",
        "app.automaticallyMatched": "Associazione automatica",
        "app.automaticallyMatchedFromFolder": "File associato automaticamente dalla cartella",
        "app.changeCursorFile": "Cambia file cursore…",
        "app.arrowFallbackDescription": "Non è stato trovato un cursore dedicato per questo ruolo, quindi viene usato il cursore standard del tema.",
        "app.automaticMatchKeywords": "Parole chiave per l'abbinamento automatico",
        "app.inheritedMatchKeywords": "Parole chiave di abbinamento ereditate",
        "app.mousecape": "Mousecape",
        "app.currentSource": "Sorgente attuale",
        "app.automaticallyMatchedInsideSelectedFolder": "Associazione automatica nella cartella selezionata",
        "app.status": "Stato",
        "app.automaticMatchFailedArrowFallbackShort": "Associazione automatica non riuscita (uso del cursore standard)",
        "app.cursorFolder": "Cartella cursori",
        "app.noFolderSelected": "Nessuna cartella selezionata",
        "app.chooseFolder": "Scegli cartella…",
        "app.cursorWillAppearHere": "Il cursore apparirà qui dopo il caricamento.",
        "export.authorLabel": "Autore",
        "export.authorPlaceholder": "Inserisci il nome autore per Mousecape",
        "export.sizeLabel": "Dimensione del cursore",
        "export.emptyAuthorTitle": "Usare il nome utente del Mac?",
        "export.emptyAuthorMessage": "Se lasci vuoto il campo autore, questo cape verrà esportato con \"%@\" come autore.",
        "export.useMacUserName": "Usa nome utente del Mac",
        "export.cancel": "Annulla",
        "export.unknownAuthor": "Sconosciuto",
        "role.arrow": "Selezione normale",
        "role.text": "Selezione testo",
        "role.link": "Selezione link",
        "role.location": "Trascina",
        "role.precision": "Selezione precisa",
        "role.move": "Sposta",
        "role.unavailable": "Non disponibile",
        "role.busy": "Occupato",
        "role.working": "Attesa",
        "role.help": "Aiuto",
        "role.handwriting": "Scrittura a mano",
        "role.person": "Selezione cella",
        "role.alternate": "Alias",
        "role.verticalResize": "Ridimensionamento verticale",
        "role.horizontalResize": "Ridimensionamento orizzontale",
        "role.diagonalResizeNWSE": "Ridimensionamento diagonale 1",
        "role.diagonalResizeNESW": "Ridimensionamento diagonale 2",
        "role.contextualMenu": "Menu contestuale",
        "role.dragCopy": "Trascina per copiare",
        "role.dragLink": "Trascina per collegare",
        "role.disappearingItem": "Elemento che scompare",
        "role.resizeUp": "Ridimensiona verso l'alto",
        "role.resizeDown": "Ridimensiona verso il basso",
        "role.resizeLeft": "Ridimensiona verso sinistra",
        "role.resizeRight": "Ridimensiona verso destra",
        "role.verticalIBeam": "Selezione testo verticale",
        "status.startingUp": "Avvio in corso...",
        "status.chooseCursorFolder": "Scegli una cartella di cursori.",
        "status.supportedFiles": "I file supportati sono .ani e .cur.",
        "status.exportSuccess": "Cape di Mousecape esportato: %@",
        "status.exportFailure": "Esportazione del cape non riuscita: %@",
        "status.loaded": "%@ caricato · %d/%d ruoli associati",
        "status.loadFailure": "Caricamento non riuscito: %@",
        "panel.chooseFolder": "Scegli cartella",
        "panel.chooseCursor": "Scegli cursore",
        "panel.export": "Esporta",
        "menu.language": "Lingua",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "Nessuna cartella del tema selezionata.",
        "error.themeFileMissing": "File del tema mancante: %@",
        "error.aniParsingFailed": "Analisi ANI non riuscita: %@",
        "error.unsupportedCursorPayload": "Impossibile leggere il fotogramma del cursore come immagine.",
        "error.invalidThemeSelection.noCursorFiles": "Questa cartella non contiene file cursore utilizzabili direttamente.\nScegli una cartella che contenga file .ani o .cur al livello superiore.",
        "error.unsupportedExtension": "Estensione non supportata: %@",
        "error.invalidRiffAconHeader": "Il file non ha un’intestazione RIFF ACON valida.",
        "error.invalidChunkLength": "La lunghezza del blocco non è valida.",
        "error.noFrames": "Il file non contiene fotogrammi.",
        "error.invalidIconChunkLength": "La lunghezza del blocco icon non è valida.",
        "error.curTooShort": "I dati CUR sono troppo corti.",
        "error.invalidCurHeader": "Il file non contiene un’intestazione CUR valida.",
        "error.invalidCurEmbeddedRange": "L’intervallo dell’immagine CUR incorporata non è valido.",
        "error.noCursorsToExport": "Non ci sono cursori da esportare."
    ]

    private static let russian: [String: String] = [
        "app.chooseCursorFolder": "Выберите папку с курсорами",
        "app.rolesReady": "Подготовлено ролей: %d",
        "app.folderRequired": "Требуется папка",
        "app.openSettings": "Открыть настройки",
        "app.quit": "Выйти",
        "app.cursors": "Курсоры",
        "app.additionalCursors": "Дополнительные курсоры",
        "app.additionalCursorUses": "Использует %@",
        "app.additionalCursorHint": "Обычно вам не нужно менять эти элементы.\nОни охватывают редко используемые состояния курсора macOS и по умолчанию сопоставляются с наиболее похожим существующим курсором.",
        "app.noCursorLoaded": "Нет загруженных курсоров",
        "app.loadCursorFolderHint": "Загрузите папку с курсорами, затем выберите роль в списке слева для предпросмотра.",
        "app.exportToMousecape": "Экспортировать как файл .cape…",
        "app.automaticMatchFailed": "Автосопоставление не удалось",
        "app.automaticMatchFailedArrowFallback": "Автосопоставление не удалось · используется обычный курсор",
        "app.manualOverride": "Ручное назначение",
        "app.automaticallyMatched": "Автосопоставление",
        "app.automaticallyMatchedFromFolder": "Файл автоматически сопоставлен из папки",
        "app.changeCursorFile": "Изменить файл курсора…",
        "app.arrowFallbackDescription": "Для этой роли не найден отдельный курсор, поэтому используется обычный курсор темы.",
        "app.automaticMatchKeywords": "Ключевые слова автосопоставления",
        "app.inheritedMatchKeywords": "Унаследованные ключевые слова сопоставления",
        "app.mousecape": "Mousecape",
        "app.currentSource": "Текущий источник",
        "app.automaticallyMatchedInsideSelectedFolder": "Автосопоставление внутри выбранной папки",
        "app.status": "Состояние",
        "app.automaticMatchFailedArrowFallbackShort": "Автосопоставление не удалось (используется обычный курсор)",
        "app.cursorFolder": "Папка курсоров",
        "app.noFolderSelected": "Папка не выбрана",
        "app.chooseFolder": "Выбрать папку…",
        "app.cursorWillAppearHere": "Курсор появится здесь после загрузки.",
        "export.authorLabel": "Автор",
        "export.authorPlaceholder": "Введите имя автора для Mousecape",
        "export.sizeLabel": "Размер курсора",
        "export.emptyAuthorTitle": "Использовать имя пользователя Mac?",
        "export.emptyAuthorMessage": "Если оставить поле автора пустым, этот cape будет экспортирован с именем автора \"%@\".",
        "export.useMacUserName": "Использовать имя пользователя Mac",
        "export.cancel": "Отмена",
        "export.unknownAuthor": "Неизвестно",
        "role.arrow": "Обычный выбор",
        "role.text": "Выбор текста",
        "role.link": "Выбор ссылки",
        "role.location": "Перетаскивание",
        "role.precision": "Точный выбор",
        "role.move": "Перемещение",
        "role.unavailable": "Недоступно",
        "role.busy": "Занят",
        "role.working": "Ожидание",
        "role.help": "Справка",
        "role.handwriting": "Рукописный ввод",
        "role.person": "Выбор ячейки",
        "role.alternate": "Псевдоним",
        "role.verticalResize": "Вертикальное изменение размера",
        "role.horizontalResize": "Горизонтальное изменение размера",
        "role.diagonalResizeNWSE": "Диагональное изменение размера 1",
        "role.diagonalResizeNESW": "Диагональное изменение размера 2",
        "role.contextualMenu": "Контекстное меню",
        "role.dragCopy": "Перетаскивание для копирования",
        "role.dragLink": "Перетаскивание для ссылки",
        "role.disappearingItem": "Исчезающий элемент",
        "role.resizeUp": "Изменение размера вверх",
        "role.resizeDown": "Изменение размера вниз",
        "role.resizeLeft": "Изменение размера влево",
        "role.resizeRight": "Изменение размера вправо",
        "role.verticalIBeam": "Вертикальное выделение текста",
        "status.startingUp": "Запуск...",
        "status.chooseCursorFolder": "Выберите папку с курсорами.",
        "status.supportedFiles": "Поддерживаются файлы .ani и .cur.",
        "status.exportSuccess": "Cape для Mousecape экспортирован: %@",
        "status.exportFailure": "Не удалось экспортировать cape: %@",
        "status.loaded": "Загружено %@ · сопоставлено %d/%d ролей",
        "status.loadFailure": "Ошибка загрузки: %@",
        "panel.chooseFolder": "Выбрать папку",
        "panel.chooseCursor": "Выбрать курсор",
        "panel.export": "Экспорт",
        "menu.language": "Язык",
        "menu.language.korean": "한국어",
        "menu.language.english": "English",
        "menu.language.japanese": "日本語",
        "menu.language.simplifiedChinese": "简体中文",
        "menu.language.traditionalChinese": "繁體中文",
        "menu.language.german": "Deutsch",
        "menu.language.french": "Français",
        "menu.language.spanish": "Español",
        "menu.language.portugueseBrazil": "Português (Brasil)",
        "menu.language.italian": "Italiano",
        "menu.language.russian": "Русский",
        "error.noThemeFolderSelected": "Папка темы не выбрана.",
        "error.themeFileMissing": "Файл темы отсутствует: %@",
        "error.aniParsingFailed": "Ошибка разбора ANI: %@",
        "error.unsupportedCursorPayload": "Не удалось прочитать кадр курсора как изображение.",
        "error.invalidThemeSelection.noCursorFiles": "В этой папке нет файлов курсоров, которые можно использовать напрямую.\nВыберите папку, в верхнем уровне которой есть файлы .ani или .cur.",
        "error.unsupportedExtension": "Неподдерживаемое расширение: %@",
        "error.invalidRiffAconHeader": "Файл не содержит корректный заголовок RIFF ACON.",
        "error.invalidChunkLength": "Недопустимая длина блока.",
        "error.noFrames": "Файл не содержит кадров.",
        "error.invalidIconChunkLength": "Недопустимая длина блока icon.",
        "error.curTooShort": "Данные CUR слишком короткие.",
        "error.invalidCurHeader": "Файл не содержит корректный заголовок CUR.",
        "error.invalidCurEmbeddedRange": "Недопустимый диапазон встроенного изображения CUR.",
        "error.noCursorsToExport": "Нет курсоров для экспорта."
    ]
}
